### ISSUE TITLE
CollectionView Horizontal scrolling doesn't work

### ISSUE THREAD

**Issue by VladislavAntonyuk** [mariusmuntean/CoordinatorLayout.Forms#1]
Add ColelctionView with horizontal scrolling in BottomView.

AR:
Only vertical scrolling is working

ER:
Horizontal scrolling should work

**Comment by mariusmuntean** [comment]
Can you describe the issue a bit more dtailed?
For example, how should the horizontal scrolling behave when the top view is expanded or collapsed?

**Comment by VladislavAntonyuk** [comment]
Please take a look at my PR. I replaced box view with button and added click command. When I click on button I expect the command is executed. Currently command is not executed.

In my project I added collection view with horizontal orientation. And horizontal scrolling doesn’t work
