### ISSUE TITLE
FYI ... I really like all of your xamarin stuff !

### ISSUE THREAD

**Issue by aktxyz** [mariusmuntean/CoordinatorLayout.Forms#4]

**Comment by aktxyz** [comment]
Can this be used or morphed into a shrinking/morphing header ... something like this?

https://www.youtube.com/watch?v=LLsibS7NeL4

I currently have a grid for a header with some extra info, and a collection view below ... when you scroll I would like the header to shrink and just have the title in a smaller font.

**Comment by mariusmuntean** [comment]
I had a look at the video and I think it can be done without any change to the library. There is no way to know for sure before trying out though 😉

The way I would approach it would be to make use of `ExpansionEventHandler` and `AutohideActionView` ([properties are explained here](https://github.com/mariusmuntean/CoordinatorLayout.Forms#property-reference)).
First, if you have some action buttons (like "Read" and "Listen" in the video) set `AutohideActionView` to `false`, so they're always shown.
Secondly, you need to react to the top view expanding/shrinking. You do this with `ExpansionEventHandler`. That gives you a value between `0.0` (meaning shrunken to the minimum value that you defined) and `1.0` (expanded to the maximum value that you defined). You can use this value to scale the title font size between a minimum font size and a maximum font size.

```
var minFontSize = 12.0f;
var maxFontSize = 24.0f;

// In your ExpansionEventHandler you receive ExpansionEventArgs args
var currentFontSize = minFontSize + (maxFontSize-minFontSize) * args.Progress;
```

Have a look at the sample app. In `CoordinatorLayoutPage` I'm using the expansion progress of the top view to change the opacity of the `BoxView` and the `Image`.
Clone the repo and run the sample app. Play with the sliders and toggles to get an intuition of what each of them does.

**Comment by mariusmuntean** [comment]
@aktxyz Check out the sample app. I whipped together an example with an expanding toolbar like in the video you posted.
