### ISSUE TITLE
Tap events not working in the "bottom" view

### ISSUE THREAD

**Issue by alokkms** [mariusmuntean/CoordinatorLayout.Forms#5]
Repro steps:
Add a "button" in the bottom view.
Add a command or Clicked event listener to the button.
Try to tap the button.

Observed:
The button command or the click event handler is never called.

Environment:
Xamarin Forms: 4.7
CoordinatorLayout.Forms: 1.2.0
OS: Android O

**Comment by mariusmuntean** [comment]
Hi there!

This is a known limitation of the library. If it works for your UX you can restrict the user interaction to the `Action View`, i.e. the `View` that hovers between the `Top View` and `Bottom View`.
Have a look at the updated sample app to get an impression of how that might look. It is an approximation of the "Listen" view from [Blinkist](https://play.google.com/store/apps/details?id=com.blinkslabs.blinkist.android&hl=en).
